### ISSUE TITLE
Image2Bag

### ISSUE THREAD

**Issue by zc-alexfan** [UnaNancyOwen/rs_bag2image#13]
Very impressive work! Thanks for sharing your code. I have RGB images (jpeg) and depth images (png) that were recorded on a realsense device, but the two images are not in the same coordinate frame, so I am trying to map depth to color. It seems that the rs library only provides the mapping for either bag files or streamed data.

So I was looking for code that can convert images to bag and do the alignment in bag files. I am wondering if you know any repository that does it? It would be nice if you could point me to a link? Thanks. :)

**Comment by UnaNancyOwen** [comment]
In rs_bag2image, the images in the bag are directly exported without align.
You can implement alignment in rs_bag2image yourself, because rs_bag2image is open source.
This sample code will be helpful to implement that feature.
https://github.com/UnaNancyOwen/RealSense2Sample/tree/master/sample/Align
